In [63]:
import numpy as np

In [64]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
arr[6]

np.int64(16)

In [67]:
arr[1:5]

array([11, 12, 13, 14])

In [68]:
arr[:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [69]:
arr[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [70]:
arr[2::3]

array([12, 15, 18])

In [73]:
arr[2::3]

array([12, 15, 18])

In [74]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [77]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [78]:
arr[1,4]

np.int64(11)

In [79]:
arr[0:2 ,4:7]

array([[ 5,  6],
       [11, 12]])

In [80]:
arr[1:,2:7]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24],
       [27, 28, 29, 30]])

In [82]:
arr[:1,:]

array([[1, 2, 3, 4, 5, 6]])

In [83]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])