In [1]:
import numpy as np

In [2]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [3]:
arr1= np.arange(31,61)
arr+arr1

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

In [5]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [6]:
arr+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

In [7]:
arr%10


array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [9, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 0]])

In [8]:
# DEEP AND SHALOW COPY

In [10]:
arr = np.array([1,2,3,4])
arr2= np.array([5,6,7,8])
slice = arr[:3]
slice

array([1, 2, 3])

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
a=arr
a[:3]

array([1, 2, 3])

In [13]:
arr

array([1, 2, 3, 4])

In [14]:
# MAtrix operation


In [22]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
b= np.arange(31,56).reshape(5,5)
b

array([[31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55]])

In [23]:
a @ b


array([[ 665,  680,  695,  710,  725],
       [1690, 1730, 1770, 1810, 1850],
       [2715, 2780, 2845, 2910, 2975],
       [3740, 3830, 3920, 4010, 4100],
       [4765, 4880, 4995, 5110, 5225]])

In [26]:
arr =np.dot(a,b)
arr

array([[ 665,  680,  695,  710,  725],
       [1690, 1730, 1770, 1810, 1850],
       [2715, 2780, 2845, 2910, 2975],
       [3740, 3830, 3920, 4010, 4100],
       [4765, 4880, 4995, 5110, 5225]])

In [27]:
arr.T

array([[ 665, 1690, 2715, 3740, 4765],
       [ 680, 1730, 2780, 3830, 4880],
       [ 695, 1770, 2845, 3920, 4995],
       [ 710, 1810, 2910, 4010, 5110],
       [ 725, 1850, 2975, 4100, 5225]])

In [ ]:
# Stack and split  Advanced

In [32]:
a= np.arange(1,4)
a

array([1, 2, 3])

In [33]:
b= np.arange(4,7)
b

array([4, 5, 6])

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [35]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.hsplit(arr,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [41]:
np.vsplit(arr,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]