In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])   # numpy creation
arr

array([1, 2, 3, 4])

In [6]:
a=[1,2,3,4,5,"hello",1.2]   # list with different data type it work perfectly
a

[1, 2, 3, 4, 5, 'hello', 1.2]

In [8]:
arr = np.array([1,2,"hello",1.2])   # if you create a numpy array with different datatype then it will convert automatically same type
arr

array(['1', '2', 'hello', '1.2'], dtype='<U32')

In [10]:
a=np.array([1.2,1,1,2])
a

array([1.2, 1. , 1. , 2. ])

In [12]:
List = [[1,2,3],[4,5,6]]   # its just create a 1d array
List

[[1, 2, 3], [4, 5, 6]]

In [13]:
np.array(List)  # it will be the 2d array


array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# Array generating function
arr =np.arange(1,11)
arr


array([1, 3, 5, 7, 9])

In [18]:
np.arange(1,11,2)   # 2 or 3 is indicates step or gap

array([1, 3, 5, 7, 9])

In [21]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [22]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.ones((6,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr = np.linspace(1,2,100)
arr

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [29]:
# Random generating function
np.random.rand(10)   # its a normalisation  its range only (0-1)

array([0.67582047, 0.27406597, 0.95249865, 0.59034538, 0.57044387,
       0.10804392, 0.00762096, 0.25385241, 0.40651059, 0.6942568 ])

In [30]:
np.random.randn(10) # its a standardisation    its range -3 to 3


array([ 0.84157211, -0.54277399, -1.44252084, -0.67028386,  1.19301653,
        2.18990648, -1.0270622 ,  0.93235023,  0.86727704,  1.93498282])

In [36]:
np.random.randint(10,100,10)

array([51, 34, 72, 71, 74, 33, 78, 59, 30, 72], dtype=int32)

In [39]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5]])
arr


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5]])

In [42]:
arr.shape

(3, 5)

In [43]:
arr.size

15

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5]])

In [46]:
arr.min

<function ndarray.min>

In [47]:
arr.min()


np.int64(0)

In [48]:
arr.max()

np.int64(9)

In [49]:
arr.sum()

np.int64(60)

In [50]:
np.sum(arr,axis=0)  # sum of all columns if i do axis 1 then rows sum

array([ 8, 11, 14, 17, 10])

In [54]:
arr.mean()

np.float64(4.0)

In [55]:
arr.std() # standard deviation


np.float64(2.581988897471611)

In [56]:
arr.argmax() # index of max elemnt

np.int64(8)

In [57]:
arr.argmin() # index of min elmt

np.int64(9)

In [59]:
arr =np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [61]:
arr= np.random.randint(1,10,30)
arr

array([5, 9, 3, 4, 1, 9, 5, 5, 3, 1, 3, 4, 4, 9, 5, 7, 8, 8, 2, 4, 3, 4,
       8, 3, 4, 6, 9, 7, 7, 6], dtype=int32)

In [62]:
arr.reshape(5,6)

array([[5, 9, 3, 4, 1, 9],
       [5, 5, 3, 1, 3, 4],
       [4, 9, 5, 7, 8, 8],
       [2, 4, 3, 4, 8, 3],
       [4, 6, 9, 7, 7, 6]], dtype=int32)